version: "3.8"

services:
  nginx:
    hostname: nginx
    image: nginx
    networks:
      - inception
    container_name: nginx
    build:
      context: requirements/nginx/
      args:
        CERTS: "${CERTS}"
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    restart: always
    ports:
      - 443:443
    volumes:
      # - type: bind
      #   source: ./requirements/nginx/conf/nginx.conf
      #   target: /etc/nginx/nginx.conf
      - wpdata:/var/www/html:ro
    depends_on:
      - wordpress
      - mariadb

  mariadb:
    image: mariadb
    container_name: $DB_HOST
    restart: always
    build:
      context: requirements/mariadb/
      args:
        MSQL_ADMIN: ${MSQL_ADMIN}
        MSQL_PW: ${MSQL_PW}
        DB_NAME: ${DB_NAME}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    volumes:
      - dbdata:$HOME/data/dbdata:/var/lib/mysql
    networks: 
      - inception
    env_file: .env

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: always
    build:
      context: requirements/wordpress/
      args:
        MSQL_ADMIN: ${MSQL_ADMIN}
        MSQL_PW: ${MSQL_PW}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN: ${WP_ADMIN}
        WP_PASS: ${WP_PASS}
        WP_MAIL: ${WP_MAIL}
    env_file: .env
    volumes:
      - wpdata:/var/www/html

    depends_on:
      - mariadb

################
##🎢 BONUS PART 🐬##

  autoheal:
    image: autoheal
    container_name: autoheal
    build:
      context: requirements/autoheal/
      args: []
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    networks:
      - inception

  ftp:
    image: ftp
    hostname: ftp
    container_name: ftp
    build:
      context: requirements/ftp
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    restart: always
    volumes:
      - wpdata:/home/ftp/${FTP_USER}
    ports:
      - 2121:21
    networks:
      - inception
    depends_on:
      - wordpress

  astro:
    hostname: astro
    image: astro
    container_name: astro
    build: requirements/astro
    restart: always
    volumes:
      - type: bind
        source: ./requirements/astro/conf/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - inception
  adminer:
    image: adminer
    container_name: adminer
    build: requirements/adminer
    restart: always
    networks:
      - inception
    ports:
      - 8080:8080
##✨ BONUS PART ✨##
################
            
networks:
  inception:
    name: inception

volumes:
  dbdata:
    name: dbdata
    driver_opts:
      device: $HOME/data/dbdata
      type: 'bind'
      o: 'bind'
  wpdata:
    name: wpdata
    driver_opts:
      device: $HOME/data/wpdata
      type: 'bind'
      o: 'bind'