version: "3.9"


services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - type: bind
        source: ./requirements/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./requirements/nginx/html/index.html
        target: /var/www/html/index.html
    networks:
      - inception

  webtest:
    image: nginx
    container_name: webtest


networks:
  inception: