version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./requirements/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./requirements/nginx/html/index.html
        target: /var/www/html/index.html
    networks:
      - inception

  # webtest:
  #   build: requirements/test/
  #   image: webtest
  #   container_name: webtest
  #   networks:
  #     - inception

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      args:
        MSQL_ADMIN: ${MSQL_ADMIN}
        MSQL_PW: ${MSQL_PW}
    restart: unless-stopped
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
    
    networks:
      - inception
    env_file:
      - .env

volumes:
  dbdata:
    name: dbdata


networks:
  inception:
    name: inception