version: "3.9"


services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx/
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./requirements/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - inception

networks:
  inception: